# contents of a minimal pyproject.toml 

[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build" 

[project] 
name = "example_package_gdang2" 
version = ["version"]
dependencies = ["numpy"]
readme="README.md"

[project.optional-dependencies]
test = ["pytest"]

[tool.hatch]
version.path = "src/example_package_gdang2/__init__.py"